# permissions for end users to view executors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: executor-viewer-role
rules:
- apiGroups:
  - executor.kubtest.io
  resources:
  - executors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - executor.kubtest.io
  resources:
  - executors/status
  verbs:
  - get
