
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - executor.kubetest.io
  resources:
  - executors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - executor.kubetest.io
  resources:
  - executors/finalizers
  verbs:
  - update
- apiGroups:
  - executor.kubetest.io
  resources:
  - executors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.kubetest.io
  resources:
  - scripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.kubetest.io
  resources:
  - scripts/finalizers
  verbs:
  - update
- apiGroups:
  - tests.kubetest.io
  resources:
  - scripts/status
  verbs:
  - get
  - patch
  - update
