# permissions for end users to view scripts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: script-viewer-role
rules:
- apiGroups:
  - tests.kubetest.io
  resources:
  - scripts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tests.kubetest.io
  resources:
  - scripts/status
  verbs:
  - get
