# permissions for end users to view testsuites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testsuite-viewer-role
rules:
- apiGroups:
  - tests.testkube.io
  resources:
  - testsuites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testsuites/status
  verbs:
  - get
