apiVersion: tests.testkube.io/v2
kind: Test
metadata:
  name: test-sample
spec:

  - type: delay
  delay: 
    duration: 1000

- type: executeScript 
  execute: 
    namespace: testkube 
    name: sanity

