apiVersion: tests.testkube.io/v1
kind: Test
metadata:
  name: test-sample
spec:
  steps: 

    - type: delay
      delay: 
        duration: 1000

    - type: executeScript 
      execute: 
        namespace: testkube 
        name: sanity
